# Makefile - RISC-V OS 
#
# Toolchain (Arch Linux uses riscv64-elf*)
TOOLCHAIN = riscv64-elf
CC = $(TOOLCHAIN)-gcc
AS = $(TOOLCHAIN)-as
LD = $(TOOLCHAIN)-ld
LDSCRIPT_SRC = linker.ld.S
LDSCRIPT = linker.ld
OBJCOPY = $(TOOLCHAIN)-objcopy
OBJDUMP = $(TOOLCHAIN)-objdump
CORE_DIR = core

# Compiler flags
CFLAGS = -march=rv32i_zicsr -mabi=ilp32 -nostdlib -fno-builtin -ffreestanding -O0 -g -I$(CORE_DIR) -Ibin/common
ASFLAGS = -march=rv32i_zicsr -mabi=ilp32
LDFLAGS = -m elf32lriscv -T $(LDSCRIPT)

# Automatic header dependency tracking: -MMD emits a .d file per 
# compiled .c, listing every header it actually included; -Mp adds
# phony targets for those headers so a deleted/renamed header doesn't
# break the build. Pulled back in near the bottom via -include
CFLAGS += -MMD -MP

# Add loglevel for the kernel
LOG_LEVEL ?= 3
CFLAGS += -DLOG_LEVEL=$(LOG_LEVEL)

define PROGRAM_RULES
bin/$(1)/$(1).elf: bin/common/crt0.o bin/common/syscall.o bin/$(1)/$(1).o bin/$(1)/linker.ld
	$$(LD) -m elf32lriscv -T bin/$(1)/linker.ld \
		bin/common/crt0.o bin/common/syscall.o bin/$(1)/$(1).o -o $$@

bin/$(1)/$(1).bin: bin/$(1)/$(1).elf
	$$(OBJCOPY) -O binary $$< $$@
endef


# Kernel-side objects: participate in the link as-is
CORE_OBJECTS = \
	boot.o \
	$(CORE_DIR)/trap.o \
	$(CORE_DIR)/trap_handler.o \
	$(CORE_DIR)/kernel.o \
	$(CORE_DIR)/uart.o \
	$(CORE_DIR)/proc.o \
	$(CORE_DIR)/panic.o


PROGRAM_OBJECTS  = $(foreach p,$(PROGRAMS),bin/$(p)/$(p).o)
PROGRAM_ELFS     = $(foreach p,$(PROGRAMS),bin/$(p)/$(p).elf)
PROGRAM_LDSCRIPTS = $(foreach p,$(PROGRAMS),bin/$(p)/linker.ld)
COMMON_OBJECTS   = bin/common/crt0.o bin/common/syscall.o
OBJECTS = $(CORE_OBJECTS)


PROGRAMS = shell yield_test
PROGRAM_BINS = $(foreach p,$(PROGRAMS),bin/$(p)/$(p).bin)
# Dependency files generated via -MMD, one per .o (kernel and user side)
DEPS = $(CORE_OBJECTS:.o=.d) bin/common/crt0.d bin/common/syscall.d \
       $(foreach p,$(PROGRAMS),bin/$(p)/$(p).d)


# Output
KERNEL = kernel.elf
 
# Targets 
.PHONY: all clean run debug disasm
 
all: $(KERNEL) $(PROGRAM_BINS)
 
# Rules
$(LDSCRIPT): $(LDSCRIPT_SRC) $(CORE_DIR)/mem_layout.h
	$(CC) -E -x assembler-with-cpp -undef -P -I$(CORE_DIR) $< -o $@
 
# Map each program to its slot index explicitly. Simple and readable
# beats clever auto-numbering for two binaries.
shell_INDEX = 0
yield_test_INDEX = 1

# Preprocess a program's own linker script, injecting its slot index.
bin/%/linker.ld: bin/%/linker.ld.S $(CORE_DIR)/mem_layout.h
	$(CC) -E -x assembler-with-cpp -undef -P -I$(CORE_DIR) \
		-DUSER_SLOT_INDEX=$($*_INDEX) $< -o $@

$(foreach p,$(PROGRAMS),$(eval $(call PROGRAM_RULES,$(p))))


$(KERNEL): $(OBJECTS) $(LDSCRIPT)
	$(LD) $(LDFLAGS) $(OBJECTS) -o $@
 
 
%.o: %.s
	$(AS) $(ASFLAGS) $< -o $@
 
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@
 
disasm: $(KERNEL)
	$(OBJDUMP) -d $(KERNEL)
run: $(KERNEL)
	qemu-system-riscv32 -M virt -bios none -kernel $(KERNEL) -nographic
debug: $(KERNEL)
	qemu-system-riscv32 -M virt -bios none -kernel $(KERNEL) \
		-gdb tcp::1234 -S -nographic &
	riscv64-elf-gdb $(KERNEL) -ex "target remote :1234"
new:
	@if [ -z "$(TYPE)" ] || [ -z "$(NAME)" ]; then \
		echo "Usage: make new TYPE=<c|h|s|ld> NAME=<filename> [LOC=<directory>]"; \
		exit 1; \
	fi
	@./tools/newfile.sh $(TYPE) $(NAME) $(LOC)


clean:
	rm -f $(CORE_OBJECTS) $(COMMON_OBJECTS) $(PROGRAM_OBJECTS) \
	      $(PROGRAM_ELFS) $(PROGRAM_BINS) $(PROGRAM_LDSCRIPTS) \
	      $(DEPS) $(KERNEL) $(LDSCRIPT)

# Pull in header dependency info generated by -MMD, if it exists yet.
-include $(DEPS)
